# API Keys (for production deployment)
[api_keys]
GTFS_VEHICLE_URL = "http://gtfs.ovapi.nl/nl/vehiclePositions.pb"
GTFS_TRIP_UPDATE_URL = "http://gtfs.ovapi.nl/nl/tripUpdates.pb"
GTFS_ALERTS_URL = "http://gtfs.ovapi.nl/nl/alerts.pb"
